version: '3.8'

services:

  backend-dev:
    # Use the development stage from our NestJS multi-stage Dockerfile
    build:
      context: ./nestjs/magic_ceipa
      target: development
    container_name: magic_nestjs_back_dev
    ports:
      # Map host port 3006 to container port 3006
      - "3006:3006"
    volumes:
      # Sync source code for live reloading
      - ./nestjs/magic_ceipa:/usr/src/app
      # Anonymous volume keeps node_modules persistent and avoids overwriting them with the host's folder
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  frontend-dev:
    # Use the development stage from our ReactJS multi-stage Dockerfile
    build:
      context: ./magicFront/magicFront
      target: development
    container_name: magic_react_front_dev
    ports:
      # Map host port 3005 to container port 3005
      - "3005:3005"
    volumes:
      # Sync source code for live reloading
      - ./magicFront/magicFront:/usr/src/app
      # Anonymous volume keeps node_modules persistent and avoids overwriting them with the host's folder
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      # Tell React to strictly bind to 3005
      - PORT=3005
      # Adding this prevents React scripts from opening the browser in the container silently failing
      - BROWSER=none
      # Allows connecting to the development server from the host
      - WDS_SOCKET_PORT=0
    restart: unless-stopped
    depends_on:
      - backend-dev

  python-backend-dev:
    build:
      context: ./planfin_microservice
      target: development
    container_name: magic_python_back_dev
    ports:
      - "3007:3007"
    volumes:
      # Sync source code for live-reloading python files
      - ./planfin_microservice:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped
