version: "3.8"

services:
  backend-prod:
    # Targets the 'production' stage which creates a much smaller, optimized image
    build:
      context: /data/magic/nestjs/magic_ceipa
      target: production
    container_name: nestjs_backend_prod
    ports:
      # In production on your Linux server, you can change the host port here
      # Format is "HOST_PORT:CONTAINER_PORT"
      - "3006:3006"
    environment:
      - NODE_ENV=production
    # In production, we do NOT map local code volumes to the container,
    # because the code is baked directly into the Docker image.
    restart: always

  frontend-prod:
    # Targets the 'production' stage which uses Nginx to serve static files
    build:
      context: /data/magic/magicFront/magicFront
      target: production
    container_name: react_frontend_prod
    ports:
      # Expose Nginx on port 80 (standard HTTP port) internally, bridged to host 3005
      # In production, you can change "80:80" to something else if using a reverse proxy
      - "3005:80"
    environment:
      - NODE_ENV=production
    # We do NOT map local code volumes here either.
    restart: always
    depends_on:
      - backend-prod

  python-backend-prod:
    build:
      context: /data/magic/planfin_microservice
      target: production
    container_name: magic_python_back_prod
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
    restart: always
