# --- BASE BUILDER ---
FROM python:3.11-slim as builder

# Prevents Python from writing pyc files and buffers stdout/stderr
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Install Libreoffice and essential build tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libreoffice-calc \
    fonts-dejavu \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
# Install dependencies into the system (or wheel)
RUN pip install --no-cache-dir -r requirements.txt


# --- DEVELOPMENT STAGE ---
FROM builder as development
WORKDIR /app
# We will mount the code via volumes in docker-compose.yml 
# so we don't need to COPY the code here.
EXPOSE 3002
# Run uvicorn with hot reload looking at /app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3002", "--reload"]


# --- PRODUCTION STAGE ---
FROM builder as production
WORKDIR /app
# Copy the actual code for production
COPY . /app

EXPOSE 3002
# Run uvicorn without hot reload for better performance
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3002"]
